# ML Service nixpacks configuration
[variables]  
FLASK_ENV = "production"

[phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "python app.py"

[phases.setup]
nixPkgs = ["python39"]