# Frontend nixpacks configuration  
[variables]
NODE_ENV = "production"
NODE_VERSION = "20.17.0"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.build]
cmds = [
    "npm ci --legacy-peer-deps --ignore-engines",
    "npm run build"
]

[phases.start]
cmd = "npx serve dist/frontend -p $PORT"