# Frontend nixpacks configuration  
[variables]
NODE_ENV = "production"

[phases.build]
cmds = [
    "npm ci --only=production",
    "npm run build --configuration=production"
]

[phases.start]
cmd = "npx serve dist/frontend -p $PORT"