version: '3.8'

services:
  # Frontend - Angular 19
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - abbrevio-network

  # Backend - Laravel 11
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-https://abbrevio-demo.up.railway.app}
      - DB_CONNECTION=mysql
      - DB_HOST=${DATABASE_URL}
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://abbrevio-demo.up.railway.app}
      - MAIL_MAILER=smtp
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME="Abbrevio Demo"
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./backend/storage:/var/www/html/storage
    depends_on:
      - database
    networks:
      - abbrevio-network

  # ML Service - Python Flask
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - BACKEND_URL=http://backend:8000
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - backend
    networks:
      - abbrevio-network

  # MySQL Database
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_DATABASE:-abbrevio}
      MYSQL_USER: ${DB_USERNAME:-abbrevio_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-abbrevio_pass}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - abbrevio-network

networks:
  abbrevio-network:
    driver: bridge

volumes:
  mysql_data: