name: abbrevio-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask=2.3.3
  - pandas=2.0.3
  - numpy=1.24.3
  - requests=2.31.0
  - pytest=7.4.2
  - scikit-learn=1.3.0
  - pip
  - pip:
    - flask-cors==4.0.0
    - python-dotenv==1.0.0
    - pytest-flask==1.2.0
