# Railway Configuration for Abbrevio
# Railway will deploy each service separately, not using docker-compose

# This file is mainly for documentation - Railway will auto-detect services
# from individual Dockerfiles in each directory

[build]
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

# Global environment variables for all services
[env]
APP_ENV = "production"
APP_DEBUG = "false"
NODE_ENV = "production"
FLASK_ENV = "production"