# Backend nixpacks configuration
[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
    "cp .env.example .env || echo 'Using existing .env'",
    "composer install --no-interaction --ignore-platform-reqs"
]

[phases.build]
cmds = [
    "php artisan config:clear || true",
    "php artisan cache:clear || true", 
    "composer install --optimize-autoloader --no-dev --no-interaction"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"